name: Deploy to pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: docker
    steps:
      - name: Checkout repository
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Setup Node.js
        uses: https://code.forgejo.org/actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Deploy
        uses: https://git.gay/gitgay/pages-deploy@v1
        with:
          folder: ./dist